// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compositions.sql

package repository

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const addCompositionRequiredPattern = `-- name: AddCompositionRequiredPattern :exec

INSERT INTO composition_required_patterns (
    composition_id, event_type, event_domain, min_occurrences
)
VALUES ($1, $2, $3, $4)
ON CONFLICT (composition_id, event_type, event_domain) DO UPDATE
    SET min_occurrences = EXCLUDED.min_occurrences
`

type AddCompositionRequiredPatternParams struct {
	CompositionID  string `json:"composition_id"`
	EventType      string `json:"event_type"`
	EventDomain    string `json:"event_domain"`
	MinOccurrences int32  `json:"min_occurrences"`
}

// ---- Required patterns per composition ----
// Maps to: PatternCompositionSpec.RequiredPatterns and MinOccurrences
func (q *Queries) AddCompositionRequiredPattern(ctx context.Context, arg AddCompositionRequiredPatternParams) error {
	_, err := q.db.Exec(ctx, addCompositionRequiredPattern,
		arg.CompositionID,
		arg.EventType,
		arg.EventDomain,
		arg.MinOccurrences,
	)
	return err
}

const createCompositionSpec = `-- name: CreateCompositionSpec :one


INSERT INTO composition_specs (
    composition_id, synapse_id,
    time_window_within, time_window_unit,
    derived_template_type, derived_template_domain, derived_template_props
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING composition_id, synapse_id, time_window_within, time_window_unit, derived_template_type, derived_template_domain, derived_template_props, created_at
`

type CreateCompositionSpecParams struct {
	CompositionID         string          `json:"composition_id"`
	SynapseID             string          `json:"synapse_id"`
	TimeWindowWithin      pgtype.Int4     `json:"time_window_within"`
	TimeWindowUnit        pgtype.Text     `json:"time_window_unit"`
	DerivedTemplateType   string          `json:"derived_template_type"`
	DerivedTemplateDomain string          `json:"derived_template_domain"`
	DerivedTemplateProps  json.RawMessage `json:"derived_template_props"`
}

// ===========================================
// Composition Specs & Required Patterns CRUD
// Maps to: PatternCompositionSpec (pattern_composition.go)
//
//	and PatternIdentifier
//
// ===========================================
// ---- Composition specs ----
func (q *Queries) CreateCompositionSpec(ctx context.Context, arg CreateCompositionSpecParams) (CompositionSpec, error) {
	row := q.db.QueryRow(ctx, createCompositionSpec,
		arg.CompositionID,
		arg.SynapseID,
		arg.TimeWindowWithin,
		arg.TimeWindowUnit,
		arg.DerivedTemplateType,
		arg.DerivedTemplateDomain,
		arg.DerivedTemplateProps,
	)
	var i CompositionSpec
	err := row.Scan(
		&i.CompositionID,
		&i.SynapseID,
		&i.TimeWindowWithin,
		&i.TimeWindowUnit,
		&i.DerivedTemplateType,
		&i.DerivedTemplateDomain,
		&i.DerivedTemplateProps,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCompositionRequiredPattern = `-- name: DeleteCompositionRequiredPattern :exec
DELETE FROM composition_required_patterns
WHERE composition_id = $1 AND event_type = $2 AND event_domain = $3
`

type DeleteCompositionRequiredPatternParams struct {
	CompositionID string `json:"composition_id"`
	EventType     string `json:"event_type"`
	EventDomain   string `json:"event_domain"`
}

func (q *Queries) DeleteCompositionRequiredPattern(ctx context.Context, arg DeleteCompositionRequiredPatternParams) error {
	_, err := q.db.Exec(ctx, deleteCompositionRequiredPattern, arg.CompositionID, arg.EventType, arg.EventDomain)
	return err
}

const deleteCompositionRequiredPatterns = `-- name: DeleteCompositionRequiredPatterns :exec
DELETE FROM composition_required_patterns
WHERE composition_id = $1
`

func (q *Queries) DeleteCompositionRequiredPatterns(ctx context.Context, compositionID string) error {
	_, err := q.db.Exec(ctx, deleteCompositionRequiredPatterns, compositionID)
	return err
}

const deleteCompositionSpec = `-- name: DeleteCompositionSpec :exec
DELETE FROM composition_specs WHERE composition_id = $1
`

func (q *Queries) DeleteCompositionSpec(ctx context.Context, compositionID string) error {
	_, err := q.db.Exec(ctx, deleteCompositionSpec, compositionID)
	return err
}

const getCompositionRequiredPatterns = `-- name: GetCompositionRequiredPatterns :many
SELECT composition_id, event_type, event_domain, min_occurrences FROM composition_required_patterns
WHERE composition_id = $1
`

func (q *Queries) GetCompositionRequiredPatterns(ctx context.Context, compositionID string) ([]CompositionRequiredPattern, error) {
	rows, err := q.db.Query(ctx, getCompositionRequiredPatterns, compositionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositionRequiredPattern{}
	for rows.Next() {
		var i CompositionRequiredPattern
		if err := rows.Scan(
			&i.CompositionID,
			&i.EventType,
			&i.EventDomain,
			&i.MinOccurrences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompositionSpec = `-- name: GetCompositionSpec :one
SELECT composition_id, synapse_id, time_window_within, time_window_unit, derived_template_type, derived_template_domain, derived_template_props, created_at FROM composition_specs WHERE composition_id = $1
`

func (q *Queries) GetCompositionSpec(ctx context.Context, compositionID string) (CompositionSpec, error) {
	row := q.db.QueryRow(ctx, getCompositionSpec, compositionID)
	var i CompositionSpec
	err := row.Scan(
		&i.CompositionID,
		&i.SynapseID,
		&i.TimeWindowWithin,
		&i.TimeWindowUnit,
		&i.DerivedTemplateType,
		&i.DerivedTemplateDomain,
		&i.DerivedTemplateProps,
		&i.CreatedAt,
	)
	return i, err
}

const listCompositionSpecs = `-- name: ListCompositionSpecs :many
SELECT composition_id, synapse_id, time_window_within, time_window_unit, derived_template_type, derived_template_domain, derived_template_props, created_at FROM composition_specs
WHERE synapse_id = $1
ORDER BY created_at
`

func (q *Queries) ListCompositionSpecs(ctx context.Context, synapseID string) ([]CompositionSpec, error) {
	rows, err := q.db.Query(ctx, listCompositionSpecs, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositionSpec{}
	for rows.Next() {
		var i CompositionSpec
		if err := rows.Scan(
			&i.CompositionID,
			&i.SynapseID,
			&i.TimeWindowWithin,
			&i.TimeWindowUnit,
			&i.DerivedTemplateType,
			&i.DerivedTemplateDomain,
			&i.DerivedTemplateProps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompositionSpec = `-- name: UpdateCompositionSpec :exec
UPDATE composition_specs SET
    time_window_within      = $2,
    time_window_unit        = $3,
    derived_template_type   = $4,
    derived_template_domain = $5,
    derived_template_props  = $6
WHERE composition_id = $1
`

type UpdateCompositionSpecParams struct {
	CompositionID         string          `json:"composition_id"`
	TimeWindowWithin      pgtype.Int4     `json:"time_window_within"`
	TimeWindowUnit        pgtype.Text     `json:"time_window_unit"`
	DerivedTemplateType   string          `json:"derived_template_type"`
	DerivedTemplateDomain string          `json:"derived_template_domain"`
	DerivedTemplateProps  json.RawMessage `json:"derived_template_props"`
}

func (q *Queries) UpdateCompositionSpec(ctx context.Context, arg UpdateCompositionSpecParams) error {
	_, err := q.db.Exec(ctx, updateCompositionSpec,
		arg.CompositionID,
		arg.TimeWindowWithin,
		arg.TimeWindowUnit,
		arg.DerivedTemplateType,
		arg.DerivedTemplateDomain,
		arg.DerivedTemplateProps,
	)
	return err
}
