// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CompositionMatchLog struct {
	ID             int64           `json:"id"`
	SynapseID      string          `json:"synapse_id"`
	CompositionID  string          `json:"composition_id"`
	RecognizedAt   time.Time       `json:"recognized_at"`
	DerivedEventID pgtype.UUID     `json:"derived_event_id"`
	Patterns       json.RawMessage `json:"patterns"`
}

type CompositionRequiredPattern struct {
	CompositionID  string `json:"composition_id"`
	EventType      string `json:"event_type"`
	EventDomain    string `json:"event_domain"`
	MinOccurrences int32  `json:"min_occurrences"`
}

type CompositionSpec struct {
	CompositionID         string          `json:"composition_id"`
	SynapseID             string          `json:"synapse_id"`
	TimeWindowWithin      pgtype.Int4     `json:"time_window_within"`
	TimeWindowUnit        pgtype.Text     `json:"time_window_unit"`
	DerivedTemplateType   string          `json:"derived_template_type"`
	DerivedTemplateDomain string          `json:"derived_template_domain"`
	DerivedTemplateProps  json.RawMessage `json:"derived_template_props"`
	CreatedAt             time.Time       `json:"created_at"`
}

type Edge struct {
	FromEventID uuid.UUID `json:"from_event_id"`
	ToEventID   uuid.UUID `json:"to_event_id"`
	Relation    string    `json:"relation"`
}

type Event struct {
	ID          uuid.UUID       `json:"id"`
	SynapseID   string          `json:"synapse_id"`
	EventType   string          `json:"event_type"`
	EventDomain string          `json:"event_domain"`
	Properties  json.RawMessage `json:"properties"`
	Timestamp   time.Time       `json:"timestamp"`
	Origin      string          `json:"origin"`
	CreatedAt   time.Time       `json:"created_at"`
}

type EventDerivation struct {
	DerivedEventID uuid.UUID   `json:"derived_event_id"`
	SynapseID      string      `json:"synapse_id"`
	OriginID       string      `json:"origin_id"`
	OriginType     string      `json:"origin_type"`
	AnchorEventID  pgtype.UUID `json:"anchor_event_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
	DerivedAt      time.Time   `json:"derived_at"`
}

type EventSignature struct {
	EventID uuid.UUID `json:"event_id"`
	Depth   int32     `json:"depth"`
	Sig     int64     `json:"sig"`
}

type LineageRuleCount struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
	RuleID        string `json:"rule_id"`
	Count         int32  `json:"count"`
}

type LineageSample struct {
	ID            int64     `json:"id"`
	SynapseID     string    `json:"synapse_id"`
	DerivedType   string    `json:"derived_type"`
	DerivedDomain string    `json:"derived_domain"`
	Depth         int32     `json:"depth"`
	Sig           int64     `json:"sig"`
	At            time.Time `json:"at"`
	RuleID        string    `json:"rule_id"`
	DerivedID     uuid.UUID `json:"derived_id"`
}

type LineageStat struct {
	SynapseID     string    `json:"synapse_id"`
	DerivedType   string    `json:"derived_type"`
	DerivedDomain string    `json:"derived_domain"`
	Depth         int32     `json:"depth"`
	Sig           int64     `json:"sig"`
	Count         int32     `json:"count"`
	LastSeen      time.Time `json:"last_seen"`
}

type MotifInstance struct {
	ID             int64       `json:"id"`
	SynapseID      string      `json:"synapse_id"`
	DerivedType    string      `json:"derived_type"`
	DerivedDomain  string      `json:"derived_domain"`
	ContributorSig string      `json:"contributor_sig"`
	RuleID         string      `json:"rule_id"`
	At             time.Time   `json:"at"`
	DerivedID      uuid.UUID   `json:"derived_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
}

type MotifStat struct {
	SynapseID      string    `json:"synapse_id"`
	DerivedType    string    `json:"derived_type"`
	DerivedDomain  string    `json:"derived_domain"`
	ContributorSig string    `json:"contributor_sig"`
	RuleID         string    `json:"rule_id"`
	Count          int32     `json:"count"`
	LastSeen       time.Time `json:"last_seen"`
}

type PatternMatchLog struct {
	ID             int64       `json:"id"`
	SynapseID      string      `json:"synapse_id"`
	DerivedType    string      `json:"derived_type"`
	DerivedDomain  string      `json:"derived_domain"`
	Depth          int32       `json:"depth"`
	Sig            int64       `json:"sig"`
	Occurrence     int32       `json:"occurrence"`
	At             time.Time   `json:"at"`
	DerivedID      uuid.UUID   `json:"derived_id"`
	RuleID         string      `json:"rule_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
	AnchorID       pgtype.UUID `json:"anchor_id"`
}

type PatternWatcherConfig struct {
	ID           string    `json:"id"`
	SynapseID    string    `json:"synapse_id"`
	Depth        int32     `json:"depth"`
	MinCount     int32     `json:"min_count"`
	DerivedTypes []string  `json:"derived_types"`
	Domains      []string  `json:"domains"`
	CreatedAt    time.Time `json:"created_at"`
}

type RevisionByEvent struct {
	EventID   uuid.UUID `json:"event_id"`
	SynapseID string    `json:"synapse_id"`
	InRev     int64     `json:"in_rev"`
	OutRev    int64     `json:"out_rev"`
}

type RevisionByType struct {
	SynapseID string `json:"synapse_id"`
	EventType string `json:"event_type"`
	TypeRev   int64  `json:"type_rev"`
}

type RevisionGlobal struct {
	SynapseID string `json:"synapse_id"`
	Revision  int64  `json:"revision"`
}

type Rule struct {
	ID             string          `json:"id"`
	SynapseID      string          `json:"synapse_id"`
	ActionType     string          `json:"action_type"`
	ConditionJson  json.RawMessage `json:"condition_json"`
	TemplateType   string          `json:"template_type"`
	TemplateDomain string          `json:"template_domain"`
	TemplateProps  json.RawMessage `json:"template_props"`
	CreatedAt      time.Time       `json:"created_at"`
}

type RuleEventType struct {
	RuleID    string `json:"rule_id"`
	EventType string `json:"event_type"`
}

type SynapseInstance struct {
	ID                   string    `json:"id"`
	Description          string    `json:"description"`
	MaxDepth             int32     `json:"max_depth"`
	MaxSamplesPerLineage int32     `json:"max_samples_per_lineage"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type WatcherCompositionLink struct {
	PatternWatcherID string `json:"pattern_watcher_id"`
	CompositionID    string `json:"composition_id"`
}
