// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: motifs.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMotifInstances = `-- name: CountMotifInstances :one
SELECT count(*) FROM motif_instances
WHERE synapse_id      = $1
  AND derived_type    = $2
  AND derived_domain  = $3
  AND contributor_sig = $4
  AND rule_id         = $5
`

type CountMotifInstancesParams struct {
	SynapseID      string `json:"synapse_id"`
	DerivedType    string `json:"derived_type"`
	DerivedDomain  string `json:"derived_domain"`
	ContributorSig string `json:"contributor_sig"`
	RuleID         string `json:"rule_id"`
}

func (q *Queries) CountMotifInstances(ctx context.Context, arg CountMotifInstancesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMotifInstances,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMotifInstance = `-- name: CreateMotifInstance :one

INSERT INTO motif_instances (
    synapse_id, derived_type, derived_domain, contributor_sig, rule_id,
    at, derived_id, contributor_ids
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, synapse_id, derived_type, derived_domain, contributor_sig, rule_id, at, derived_id, contributor_ids
`

type CreateMotifInstanceParams struct {
	SynapseID      string      `json:"synapse_id"`
	DerivedType    string      `json:"derived_type"`
	DerivedDomain  string      `json:"derived_domain"`
	ContributorSig string      `json:"contributor_sig"`
	RuleID         string      `json:"rule_id"`
	At             time.Time   `json:"at"`
	DerivedID      uuid.UUID   `json:"derived_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
}

// ---- Motif instances ----
func (q *Queries) CreateMotifInstance(ctx context.Context, arg CreateMotifInstanceParams) (MotifInstance, error) {
	row := q.db.QueryRow(ctx, createMotifInstance,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
		arg.At,
		arg.DerivedID,
		arg.ContributorIds,
	)
	var i MotifInstance
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.DerivedType,
		&i.DerivedDomain,
		&i.ContributorSig,
		&i.RuleID,
		&i.At,
		&i.DerivedID,
		&i.ContributorIds,
	)
	return i, err
}

const deleteMotifInstances = `-- name: DeleteMotifInstances :exec
DELETE FROM motif_instances
WHERE synapse_id      = $1
  AND derived_type    = $2
  AND derived_domain  = $3
  AND contributor_sig = $4
  AND rule_id         = $5
`

type DeleteMotifInstancesParams struct {
	SynapseID      string `json:"synapse_id"`
	DerivedType    string `json:"derived_type"`
	DerivedDomain  string `json:"derived_domain"`
	ContributorSig string `json:"contributor_sig"`
	RuleID         string `json:"rule_id"`
}

func (q *Queries) DeleteMotifInstances(ctx context.Context, arg DeleteMotifInstancesParams) error {
	_, err := q.db.Exec(ctx, deleteMotifInstances,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
	)
	return err
}

const deleteMotifStats = `-- name: DeleteMotifStats :exec
DELETE FROM motif_stats
WHERE synapse_id      = $1
  AND derived_type    = $2
  AND derived_domain  = $3
  AND contributor_sig = $4
  AND rule_id         = $5
`

type DeleteMotifStatsParams struct {
	SynapseID      string `json:"synapse_id"`
	DerivedType    string `json:"derived_type"`
	DerivedDomain  string `json:"derived_domain"`
	ContributorSig string `json:"contributor_sig"`
	RuleID         string `json:"rule_id"`
}

func (q *Queries) DeleteMotifStats(ctx context.Context, arg DeleteMotifStatsParams) error {
	_, err := q.db.Exec(ctx, deleteMotifStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
	)
	return err
}

const getAllMotifInstancesBySynapse = `-- name: GetAllMotifInstancesBySynapse :many
SELECT id, synapse_id, derived_type, derived_domain, contributor_sig, rule_id, at, derived_id, contributor_ids FROM motif_instances
WHERE synapse_id = $1
ORDER BY at DESC
`

func (q *Queries) GetAllMotifInstancesBySynapse(ctx context.Context, synapseID string) ([]MotifInstance, error) {
	rows, err := q.db.Query(ctx, getAllMotifInstancesBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MotifInstance{}
	for rows.Next() {
		var i MotifInstance
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.ContributorSig,
			&i.RuleID,
			&i.At,
			&i.DerivedID,
			&i.ContributorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMotifInstances = `-- name: GetMotifInstances :many
SELECT id, synapse_id, derived_type, derived_domain, contributor_sig, rule_id, at, derived_id, contributor_ids FROM motif_instances
WHERE synapse_id      = $1
  AND derived_type    = $2
  AND derived_domain  = $3
  AND contributor_sig = $4
  AND rule_id         = $5
ORDER BY at DESC
`

type GetMotifInstancesParams struct {
	SynapseID      string `json:"synapse_id"`
	DerivedType    string `json:"derived_type"`
	DerivedDomain  string `json:"derived_domain"`
	ContributorSig string `json:"contributor_sig"`
	RuleID         string `json:"rule_id"`
}

func (q *Queries) GetMotifInstances(ctx context.Context, arg GetMotifInstancesParams) ([]MotifInstance, error) {
	rows, err := q.db.Query(ctx, getMotifInstances,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MotifInstance{}
	for rows.Next() {
		var i MotifInstance
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.ContributorSig,
			&i.RuleID,
			&i.At,
			&i.DerivedID,
			&i.ContributorIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMotifStats = `-- name: GetMotifStats :one
SELECT synapse_id, derived_type, derived_domain, contributor_sig, rule_id, count, last_seen FROM motif_stats
WHERE synapse_id      = $1
  AND derived_type    = $2
  AND derived_domain  = $3
  AND contributor_sig = $4
  AND rule_id         = $5
`

type GetMotifStatsParams struct {
	SynapseID      string `json:"synapse_id"`
	DerivedType    string `json:"derived_type"`
	DerivedDomain  string `json:"derived_domain"`
	ContributorSig string `json:"contributor_sig"`
	RuleID         string `json:"rule_id"`
}

func (q *Queries) GetMotifStats(ctx context.Context, arg GetMotifStatsParams) (MotifStat, error) {
	row := q.db.QueryRow(ctx, getMotifStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
	)
	var i MotifStat
	err := row.Scan(
		&i.SynapseID,
		&i.DerivedType,
		&i.DerivedDomain,
		&i.ContributorSig,
		&i.RuleID,
		&i.Count,
		&i.LastSeen,
	)
	return i, err
}

const incrementMotifStats = `-- name: IncrementMotifStats :exec


INSERT INTO motif_stats (synapse_id, derived_type, derived_domain, contributor_sig, rule_id, count, last_seen)
VALUES ($1, $2, $3, $4, $5, 1, $6)
ON CONFLICT (synapse_id, derived_type, derived_domain, contributor_sig, rule_id) DO UPDATE
    SET count     = motif_stats.count + 1,
        last_seen = EXCLUDED.last_seen
`

type IncrementMotifStatsParams struct {
	SynapseID      string    `json:"synapse_id"`
	DerivedType    string    `json:"derived_type"`
	DerivedDomain  string    `json:"derived_domain"`
	ContributorSig string    `json:"contributor_sig"`
	RuleID         string    `json:"rule_id"`
	LastSeen       time.Time `json:"last_seen"`
}

// ===========================================
// Motif Stats & Instances CRUD
// Maps to: motifs map[MotifKey]*MotifStats
//
//	in InMemoryStructuralMemory
//
// ===========================================
// ---- Motif stats ----
func (q *Queries) IncrementMotifStats(ctx context.Context, arg IncrementMotifStatsParams) error {
	_, err := q.db.Exec(ctx, incrementMotifStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
		arg.LastSeen,
	)
	return err
}

const listMotifStats = `-- name: ListMotifStats :many
SELECT synapse_id, derived_type, derived_domain, contributor_sig, rule_id, count, last_seen FROM motif_stats
WHERE synapse_id = $1
ORDER BY last_seen DESC
`

func (q *Queries) ListMotifStats(ctx context.Context, synapseID string) ([]MotifStat, error) {
	rows, err := q.db.Query(ctx, listMotifStats, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MotifStat{}
	for rows.Next() {
		var i MotifStat
		if err := rows.Scan(
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.ContributorSig,
			&i.RuleID,
			&i.Count,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMotifStats = `-- name: UpsertMotifStats :exec
INSERT INTO motif_stats (synapse_id, derived_type, derived_domain, contributor_sig, rule_id, count, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (synapse_id, derived_type, derived_domain, contributor_sig, rule_id) DO UPDATE
    SET count     = EXCLUDED.count,
        last_seen = EXCLUDED.last_seen
`

type UpsertMotifStatsParams struct {
	SynapseID      string    `json:"synapse_id"`
	DerivedType    string    `json:"derived_type"`
	DerivedDomain  string    `json:"derived_domain"`
	ContributorSig string    `json:"contributor_sig"`
	RuleID         string    `json:"rule_id"`
	Count          int32     `json:"count"`
	LastSeen       time.Time `json:"last_seen"`
}

func (q *Queries) UpsertMotifStats(ctx context.Context, arg UpsertMotifStatsParams) error {
	_, err := q.db.Exec(ctx, upsertMotifStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.ContributorSig,
		arg.RuleID,
		arg.Count,
		arg.LastSeen,
	)
	return err
}
