// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pattern_watchers.sql

package repository

import (
	"context"
)

const createPatternWatcherConfig = `-- name: CreatePatternWatcherConfig :one

INSERT INTO pattern_watcher_configs (id, synapse_id, depth, min_count, derived_types, domains)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, synapse_id, depth, min_count, derived_types, domains, created_at
`

type CreatePatternWatcherConfigParams struct {
	ID           string   `json:"id"`
	SynapseID    string   `json:"synapse_id"`
	Depth        int32    `json:"depth"`
	MinCount     int32    `json:"min_count"`
	DerivedTypes []string `json:"derived_types"`
	Domains      []string `json:"domains"`
}

// ===========================================
// Pattern Watcher Configs CRUD
// Maps to: PatternWatcher / PatternConfig (pattern_watcher.go)
//
//	and WatchSpec (pattern_watcher.go)
//
// ===========================================
func (q *Queries) CreatePatternWatcherConfig(ctx context.Context, arg CreatePatternWatcherConfigParams) (PatternWatcherConfig, error) {
	row := q.db.QueryRow(ctx, createPatternWatcherConfig,
		arg.ID,
		arg.SynapseID,
		arg.Depth,
		arg.MinCount,
		arg.DerivedTypes,
		arg.Domains,
	)
	var i PatternWatcherConfig
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.Depth,
		&i.MinCount,
		&i.DerivedTypes,
		&i.Domains,
		&i.CreatedAt,
	)
	return i, err
}

const deletePatternWatcherConfig = `-- name: DeletePatternWatcherConfig :exec
DELETE FROM pattern_watcher_configs WHERE id = $1
`

func (q *Queries) DeletePatternWatcherConfig(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePatternWatcherConfig, id)
	return err
}

const getPatternWatcherConfig = `-- name: GetPatternWatcherConfig :one
SELECT id, synapse_id, depth, min_count, derived_types, domains, created_at FROM pattern_watcher_configs WHERE id = $1
`

func (q *Queries) GetPatternWatcherConfig(ctx context.Context, id string) (PatternWatcherConfig, error) {
	row := q.db.QueryRow(ctx, getPatternWatcherConfig, id)
	var i PatternWatcherConfig
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.Depth,
		&i.MinCount,
		&i.DerivedTypes,
		&i.Domains,
		&i.CreatedAt,
	)
	return i, err
}

const listPatternWatcherConfigs = `-- name: ListPatternWatcherConfigs :many
SELECT id, synapse_id, depth, min_count, derived_types, domains, created_at FROM pattern_watcher_configs
WHERE synapse_id = $1
ORDER BY created_at
`

func (q *Queries) ListPatternWatcherConfigs(ctx context.Context, synapseID string) ([]PatternWatcherConfig, error) {
	rows, err := q.db.Query(ctx, listPatternWatcherConfigs, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatternWatcherConfig{}
	for rows.Next() {
		var i PatternWatcherConfig
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.Depth,
			&i.MinCount,
			&i.DerivedTypes,
			&i.Domains,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatternWatcherConfig = `-- name: UpdatePatternWatcherConfig :exec
UPDATE pattern_watcher_configs SET
    depth         = $2,
    min_count     = $3,
    derived_types = $4,
    domains       = $5
WHERE id = $1
`

type UpdatePatternWatcherConfigParams struct {
	ID           string   `json:"id"`
	Depth        int32    `json:"depth"`
	MinCount     int32    `json:"min_count"`
	DerivedTypes []string `json:"derived_types"`
	Domains      []string `json:"domains"`
}

func (q *Queries) UpdatePatternWatcherConfig(ctx context.Context, arg UpdatePatternWatcherConfigParams) error {
	_, err := q.db.Exec(ctx, updatePatternWatcherConfig,
		arg.ID,
		arg.Depth,
		arg.MinCount,
		arg.DerivedTypes,
		arg.Domains,
	)
	return err
}
