// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rules.sql

package repository

import (
	"context"
	"encoding/json"
)

const addRuleEventType = `-- name: AddRuleEventType :exec

INSERT INTO rule_event_types (rule_id, event_type)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRuleEventTypeParams struct {
	RuleID    string `json:"rule_id"`
	EventType string `json:"event_type"`
}

// ---- Rule <-> EventType bindings ----
// Maps to: RegisterRule / RegisterRuleForTypes
func (q *Queries) AddRuleEventType(ctx context.Context, arg AddRuleEventTypeParams) error {
	_, err := q.db.Exec(ctx, addRuleEventType, arg.RuleID, arg.EventType)
	return err
}

const createRule = `-- name: CreateRule :one


INSERT INTO rules (
    id, synapse_id, action_type, condition_json,
    template_type, template_domain, template_props
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, synapse_id, action_type, condition_json, template_type, template_domain, template_props, created_at
`

type CreateRuleParams struct {
	ID             string          `json:"id"`
	SynapseID      string          `json:"synapse_id"`
	ActionType     string          `json:"action_type"`
	ConditionJson  json.RawMessage `json:"condition_json"`
	TemplateType   string          `json:"template_type"`
	TemplateDomain string          `json:"template_domain"`
	TemplateProps  json.RawMessage `json:"template_props"`
}

// ===========================================
// Rules & Rule-EventType Bindings CRUD
// Maps to: DeriveEventRule (rules.go)
//
//	and SynapseRuntime.rulesByType (synapse_runtime.go)
//
// ===========================================
// ---- Rules ----
func (q *Queries) CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error) {
	row := q.db.QueryRow(ctx, createRule,
		arg.ID,
		arg.SynapseID,
		arg.ActionType,
		arg.ConditionJson,
		arg.TemplateType,
		arg.TemplateDomain,
		arg.TemplateProps,
	)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.ActionType,
		&i.ConditionJson,
		&i.TemplateType,
		&i.TemplateDomain,
		&i.TemplateProps,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRule = `-- name: DeleteRule :exec
DELETE FROM rules WHERE id = $1
`

func (q *Queries) DeleteRule(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteRule, id)
	return err
}

const deleteRuleEventType = `-- name: DeleteRuleEventType :exec
DELETE FROM rule_event_types
WHERE rule_id = $1 AND event_type = $2
`

type DeleteRuleEventTypeParams struct {
	RuleID    string `json:"rule_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) DeleteRuleEventType(ctx context.Context, arg DeleteRuleEventTypeParams) error {
	_, err := q.db.Exec(ctx, deleteRuleEventType, arg.RuleID, arg.EventType)
	return err
}

const deleteRuleEventTypes = `-- name: DeleteRuleEventTypes :exec
DELETE FROM rule_event_types WHERE rule_id = $1
`

func (q *Queries) DeleteRuleEventTypes(ctx context.Context, ruleID string) error {
	_, err := q.db.Exec(ctx, deleteRuleEventTypes, ruleID)
	return err
}

const getRule = `-- name: GetRule :one
SELECT id, synapse_id, action_type, condition_json, template_type, template_domain, template_props, created_at FROM rules WHERE id = $1
`

func (q *Queries) GetRule(ctx context.Context, id string) (Rule, error) {
	row := q.db.QueryRow(ctx, getRule, id)
	var i Rule
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.ActionType,
		&i.ConditionJson,
		&i.TemplateType,
		&i.TemplateDomain,
		&i.TemplateProps,
		&i.CreatedAt,
	)
	return i, err
}

const getRuleEventTypes = `-- name: GetRuleEventTypes :many
SELECT rule_id, event_type FROM rule_event_types WHERE rule_id = $1
`

func (q *Queries) GetRuleEventTypes(ctx context.Context, ruleID string) ([]RuleEventType, error) {
	rows, err := q.db.Query(ctx, getRuleEventTypes, ruleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleEventType{}
	for rows.Next() {
		var i RuleEventType
		if err := rows.Scan(&i.RuleID, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRulesByEventType = `-- name: GetRulesByEventType :many
SELECT r.id, r.synapse_id, r.action_type, r.condition_json, r.template_type, r.template_domain, r.template_props, r.created_at
FROM rules r
JOIN rule_event_types ret ON r.id = ret.rule_id
WHERE ret.event_type = $1 AND r.synapse_id = $2
`

type GetRulesByEventTypeParams struct {
	EventType string `json:"event_type"`
	SynapseID string `json:"synapse_id"`
}

func (q *Queries) GetRulesByEventType(ctx context.Context, arg GetRulesByEventTypeParams) ([]Rule, error) {
	rows, err := q.db.Query(ctx, getRulesByEventType, arg.EventType, arg.SynapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.ActionType,
			&i.ConditionJson,
			&i.TemplateType,
			&i.TemplateDomain,
			&i.TemplateProps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuleEventTypesBySynapse = `-- name: ListRuleEventTypesBySynapse :many
SELECT ret.rule_id, ret.event_type
FROM rule_event_types ret
JOIN rules r ON ret.rule_id = r.id
WHERE r.synapse_id = $1
`

func (q *Queries) ListRuleEventTypesBySynapse(ctx context.Context, synapseID string) ([]RuleEventType, error) {
	rows, err := q.db.Query(ctx, listRuleEventTypesBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RuleEventType{}
	for rows.Next() {
		var i RuleEventType
		if err := rows.Scan(&i.RuleID, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRules = `-- name: ListRules :many
SELECT id, synapse_id, action_type, condition_json, template_type, template_domain, template_props, created_at FROM rules
WHERE synapse_id = $1
ORDER BY created_at
`

func (q *Queries) ListRules(ctx context.Context, synapseID string) ([]Rule, error) {
	rows, err := q.db.Query(ctx, listRules, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Rule{}
	for rows.Next() {
		var i Rule
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.ActionType,
			&i.ConditionJson,
			&i.TemplateType,
			&i.TemplateDomain,
			&i.TemplateProps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRule = `-- name: UpdateRule :exec
UPDATE rules SET
    action_type     = $2,
    condition_json  = $3,
    template_type   = $4,
    template_domain = $5,
    template_props  = $6
WHERE id = $1
`

type UpdateRuleParams struct {
	ID             string          `json:"id"`
	ActionType     string          `json:"action_type"`
	ConditionJson  json.RawMessage `json:"condition_json"`
	TemplateType   string          `json:"template_type"`
	TemplateDomain string          `json:"template_domain"`
	TemplateProps  json.RawMessage `json:"template_props"`
}

func (q *Queries) UpdateRule(ctx context.Context, arg UpdateRuleParams) error {
	_, err := q.db.Exec(ctx, updateRule,
		arg.ID,
		arg.ActionType,
		arg.ConditionJson,
		arg.TemplateType,
		arg.TemplateDomain,
		arg.TemplateProps,
	)
	return err
}
