// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: signatures.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteEventSignatures = `-- name: DeleteEventSignatures :exec
DELETE FROM event_signatures WHERE event_id = $1
`

func (q *Queries) DeleteEventSignatures(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventSignatures, eventID)
	return err
}

const getEventSignature = `-- name: GetEventSignature :one
SELECT event_id, depth, sig FROM event_signatures
WHERE event_id = $1 AND depth = $2
`

type GetEventSignatureParams struct {
	EventID uuid.UUID `json:"event_id"`
	Depth   int32     `json:"depth"`
}

func (q *Queries) GetEventSignature(ctx context.Context, arg GetEventSignatureParams) (EventSignature, error) {
	row := q.db.QueryRow(ctx, getEventSignature, arg.EventID, arg.Depth)
	var i EventSignature
	err := row.Scan(&i.EventID, &i.Depth, &i.Sig)
	return i, err
}

const getEventSignatures = `-- name: GetEventSignatures :many
SELECT event_id, depth, sig FROM event_signatures
WHERE event_id = $1
ORDER BY depth
`

func (q *Queries) GetEventSignatures(ctx context.Context, eventID uuid.UUID) ([]EventSignature, error) {
	rows, err := q.db.Query(ctx, getEventSignatures, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSignature{}
	for rows.Next() {
		var i EventSignature
		if err := rows.Scan(&i.EventID, &i.Depth, &i.Sig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSignaturesBySynapse = `-- name: GetSignaturesBySynapse :many
SELECT es.event_id, es.depth, es.sig FROM event_signatures es
JOIN events ev ON es.event_id = ev.id
WHERE ev.synapse_id = $1
ORDER BY es.event_id, es.depth
`

func (q *Queries) GetSignaturesBySynapse(ctx context.Context, synapseID string) ([]EventSignature, error) {
	rows, err := q.db.Query(ctx, getSignaturesBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventSignature{}
	for rows.Next() {
		var i EventSignature
		if err := rows.Scan(&i.EventID, &i.Depth, &i.Sig); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEventSignature = `-- name: UpsertEventSignature :exec

INSERT INTO event_signatures (event_id, depth, sig)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, depth) DO UPDATE
    SET sig = EXCLUDED.sig
`

type UpsertEventSignatureParams struct {
	EventID uuid.UUID `json:"event_id"`
	Depth   int32     `json:"depth"`
	Sig     int64     `json:"sig"`
}

// ===========================================
// Event Signatures CRUD
// Maps to: sigs map[EventID][]uint64
//
//	in InMemoryStructuralMemory
//
// ===========================================
func (q *Queries) UpsertEventSignature(ctx context.Context, arg UpsertEventSignatureParams) error {
	_, err := q.db.Exec(ctx, upsertEventSignature, arg.EventID, arg.Depth, arg.Sig)
	return err
}
