// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompositionMatchLog = `-- name: CreateCompositionMatchLog :one

INSERT INTO composition_match_log (
    synapse_id, composition_id, recognized_at, derived_event_id, patterns
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, synapse_id, composition_id, recognized_at, derived_event_id, patterns
`

type CreateCompositionMatchLogParams struct {
	SynapseID      string          `json:"synapse_id"`
	CompositionID  string          `json:"composition_id"`
	RecognizedAt   time.Time       `json:"recognized_at"`
	DerivedEventID pgtype.UUID     `json:"derived_event_id"`
	Patterns       json.RawMessage `json:"patterns"`
}

// ---- Composition match log ----
func (q *Queries) CreateCompositionMatchLog(ctx context.Context, arg CreateCompositionMatchLogParams) (CompositionMatchLog, error) {
	row := q.db.QueryRow(ctx, createCompositionMatchLog,
		arg.SynapseID,
		arg.CompositionID,
		arg.RecognizedAt,
		arg.DerivedEventID,
		arg.Patterns,
	)
	var i CompositionMatchLog
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.CompositionID,
		&i.RecognizedAt,
		&i.DerivedEventID,
		&i.Patterns,
	)
	return i, err
}

const createPatternMatchLog = `-- name: CreatePatternMatchLog :one


INSERT INTO pattern_match_log (
    synapse_id,
    derived_type, derived_domain, depth, sig,
    occurrence, at, derived_id, rule_id,
    contributor_ids, anchor_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, synapse_id, derived_type, derived_domain, depth, sig, occurrence, at, derived_id, rule_id, contributor_ids, anchor_id
`

type CreatePatternMatchLogParams struct {
	SynapseID      string      `json:"synapse_id"`
	DerivedType    string      `json:"derived_type"`
	DerivedDomain  string      `json:"derived_domain"`
	Depth          int32       `json:"depth"`
	Sig            int64       `json:"sig"`
	Occurrence     int32       `json:"occurrence"`
	At             time.Time   `json:"at"`
	DerivedID      uuid.UUID   `json:"derived_id"`
	RuleID         string      `json:"rule_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
	AnchorID       pgtype.UUID `json:"anchor_id"`
}

// ===========================================
// Audit / Logging CRUD
// Maps to: PatternMatch (pattern_watcher.go)
//
//	and PatternCompositionMatch (pattern_composition.go)
//
// ===========================================
// ---- Pattern match log ----
func (q *Queries) CreatePatternMatchLog(ctx context.Context, arg CreatePatternMatchLogParams) (PatternMatchLog, error) {
	row := q.db.QueryRow(ctx, createPatternMatchLog,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
		arg.Occurrence,
		arg.At,
		arg.DerivedID,
		arg.RuleID,
		arg.ContributorIds,
		arg.AnchorID,
	)
	var i PatternMatchLog
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.DerivedType,
		&i.DerivedDomain,
		&i.Depth,
		&i.Sig,
		&i.Occurrence,
		&i.At,
		&i.DerivedID,
		&i.RuleID,
		&i.ContributorIds,
		&i.AnchorID,
	)
	return i, err
}

const deleteCompositionMatchLog = `-- name: DeleteCompositionMatchLog :exec
DELETE FROM composition_match_log WHERE id = $1
`

func (q *Queries) DeleteCompositionMatchLog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCompositionMatchLog, id)
	return err
}

const deletePatternMatchLog = `-- name: DeletePatternMatchLog :exec
DELETE FROM pattern_match_log WHERE id = $1
`

func (q *Queries) DeletePatternMatchLog(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePatternMatchLog, id)
	return err
}

const getPatternMatchLogsByDerivedID = `-- name: GetPatternMatchLogsByDerivedID :many
SELECT id, synapse_id, derived_type, derived_domain, depth, sig, occurrence, at, derived_id, rule_id, contributor_ids, anchor_id FROM pattern_match_log
WHERE derived_id = $1
`

func (q *Queries) GetPatternMatchLogsByDerivedID(ctx context.Context, derivedID uuid.UUID) ([]PatternMatchLog, error) {
	rows, err := q.db.Query(ctx, getPatternMatchLogsByDerivedID, derivedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatternMatchLog{}
	for rows.Next() {
		var i PatternMatchLog
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.Occurrence,
			&i.At,
			&i.DerivedID,
			&i.RuleID,
			&i.ContributorIds,
			&i.AnchorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompositionMatchLogs = `-- name: ListCompositionMatchLogs :many
SELECT id, synapse_id, composition_id, recognized_at, derived_event_id, patterns FROM composition_match_log
WHERE synapse_id = $1
ORDER BY recognized_at DESC
LIMIT $2 OFFSET $3
`

type ListCompositionMatchLogsParams struct {
	SynapseID string `json:"synapse_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListCompositionMatchLogs(ctx context.Context, arg ListCompositionMatchLogsParams) ([]CompositionMatchLog, error) {
	rows, err := q.db.Query(ctx, listCompositionMatchLogs, arg.SynapseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositionMatchLog{}
	for rows.Next() {
		var i CompositionMatchLog
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.CompositionID,
			&i.RecognizedAt,
			&i.DerivedEventID,
			&i.Patterns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompositionMatchLogsBySpec = `-- name: ListCompositionMatchLogsBySpec :many
SELECT id, synapse_id, composition_id, recognized_at, derived_event_id, patterns FROM composition_match_log
WHERE synapse_id = $1 AND composition_id = $2
ORDER BY recognized_at DESC
LIMIT $3 OFFSET $4
`

type ListCompositionMatchLogsBySpecParams struct {
	SynapseID     string `json:"synapse_id"`
	CompositionID string `json:"composition_id"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) ListCompositionMatchLogsBySpec(ctx context.Context, arg ListCompositionMatchLogsBySpecParams) ([]CompositionMatchLog, error) {
	rows, err := q.db.Query(ctx, listCompositionMatchLogsBySpec,
		arg.SynapseID,
		arg.CompositionID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositionMatchLog{}
	for rows.Next() {
		var i CompositionMatchLog
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.CompositionID,
			&i.RecognizedAt,
			&i.DerivedEventID,
			&i.Patterns,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatternMatchLogs = `-- name: ListPatternMatchLogs :many
SELECT id, synapse_id, derived_type, derived_domain, depth, sig, occurrence, at, derived_id, rule_id, contributor_ids, anchor_id FROM pattern_match_log
WHERE synapse_id = $1
ORDER BY at DESC
LIMIT $2 OFFSET $3
`

type ListPatternMatchLogsParams struct {
	SynapseID string `json:"synapse_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListPatternMatchLogs(ctx context.Context, arg ListPatternMatchLogsParams) ([]PatternMatchLog, error) {
	rows, err := q.db.Query(ctx, listPatternMatchLogs, arg.SynapseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatternMatchLog{}
	for rows.Next() {
		var i PatternMatchLog
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.Occurrence,
			&i.At,
			&i.DerivedID,
			&i.RuleID,
			&i.ContributorIds,
			&i.AnchorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatternMatchLogsByType = `-- name: ListPatternMatchLogsByType :many
SELECT id, synapse_id, derived_type, derived_domain, depth, sig, occurrence, at, derived_id, rule_id, contributor_ids, anchor_id FROM pattern_match_log
WHERE synapse_id = $1 AND derived_type = $2 AND derived_domain = $3
ORDER BY at DESC
LIMIT $4 OFFSET $5
`

type ListPatternMatchLogsByTypeParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Limit         int32  `json:"limit"`
	Offset        int32  `json:"offset"`
}

func (q *Queries) ListPatternMatchLogsByType(ctx context.Context, arg ListPatternMatchLogsByTypeParams) ([]PatternMatchLog, error) {
	rows, err := q.db.Query(ctx, listPatternMatchLogsByType,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatternMatchLog{}
	for rows.Next() {
		var i PatternMatchLog
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.Occurrence,
			&i.At,
			&i.DerivedID,
			&i.RuleID,
			&i.ContributorIds,
			&i.AnchorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
