// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createEdge = `-- name: CreateEdge :exec

INSERT INTO edges (from_event_id, to_event_id, relation)
VALUES ($1, $2, $3)
`

type CreateEdgeParams struct {
	FromEventID uuid.UUID `json:"from_event_id"`
	ToEventID   uuid.UUID `json:"to_event_id"`
	Relation    string    `json:"relation"`
}

// ===========================================
// Edges CRUD
// Maps to: Edge (edge.go)
// ===========================================
func (q *Queries) CreateEdge(ctx context.Context, arg CreateEdgeParams) error {
	_, err := q.db.Exec(ctx, createEdge, arg.FromEventID, arg.ToEventID, arg.Relation)
	return err
}

const deleteEdge = `-- name: DeleteEdge :exec
DELETE FROM edges
WHERE from_event_id = $1 AND to_event_id = $2 AND relation = $3
`

type DeleteEdgeParams struct {
	FromEventID uuid.UUID `json:"from_event_id"`
	ToEventID   uuid.UUID `json:"to_event_id"`
	Relation    string    `json:"relation"`
}

func (q *Queries) DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteEdge, arg.FromEventID, arg.ToEventID, arg.Relation)
	return err
}

const deleteEdgesFrom = `-- name: DeleteEdgesFrom :exec
DELETE FROM edges WHERE from_event_id = $1
`

func (q *Queries) DeleteEdgesFrom(ctx context.Context, fromEventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdgesFrom, fromEventID)
	return err
}

const deleteEdgesTo = `-- name: DeleteEdgesTo :exec
DELETE FROM edges WHERE to_event_id = $1
`

func (q *Queries) DeleteEdgesTo(ctx context.Context, toEventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEdgesTo, toEventID)
	return err
}

const getEdge = `-- name: GetEdge :one
SELECT from_event_id, to_event_id, relation FROM edges
WHERE from_event_id = $1 AND to_event_id = $2 AND relation = $3
`

type GetEdgeParams struct {
	FromEventID uuid.UUID `json:"from_event_id"`
	ToEventID   uuid.UUID `json:"to_event_id"`
	Relation    string    `json:"relation"`
}

func (q *Queries) GetEdge(ctx context.Context, arg GetEdgeParams) (Edge, error) {
	row := q.db.QueryRow(ctx, getEdge, arg.FromEventID, arg.ToEventID, arg.Relation)
	var i Edge
	err := row.Scan(&i.FromEventID, &i.ToEventID, &i.Relation)
	return i, err
}

const getEdgesBySynapse = `-- name: GetEdgesBySynapse :many
SELECT e.from_event_id, e.to_event_id, e.relation FROM edges e
JOIN events ev ON e.from_event_id = ev.id
WHERE ev.synapse_id = $1
`

func (q *Queries) GetEdgesBySynapse(ctx context.Context, synapseID string) ([]Edge, error) {
	rows, err := q.db.Query(ctx, getEdgesBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(&i.FromEventID, &i.ToEventID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesFrom = `-- name: GetEdgesFrom :many
SELECT from_event_id, to_event_id, relation FROM edges WHERE from_event_id = $1
`

func (q *Queries) GetEdgesFrom(ctx context.Context, fromEventID uuid.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, getEdgesFrom, fromEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(&i.FromEventID, &i.ToEventID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEdgesTo = `-- name: GetEdgesTo :many
SELECT from_event_id, to_event_id, relation FROM edges WHERE to_event_id = $1
`

func (q *Queries) GetEdgesTo(ctx context.Context, toEventID uuid.UUID) ([]Edge, error) {
	rows, err := q.db.Query(ctx, getEdgesTo, toEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Edge{}
	for rows.Next() {
		var i Edge
		if err := rows.Scan(&i.FromEventID, &i.ToEventID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
