// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_derivations.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDerivationsBySynapse = `-- name: CountDerivationsBySynapse :one
SELECT count(*) FROM event_derivations WHERE synapse_id = $1
`

func (q *Queries) CountDerivationsBySynapse(ctx context.Context, synapseID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDerivationsBySynapse, synapseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEventDerivation = `-- name: CreateEventDerivation :exec

INSERT INTO event_derivations (
    derived_event_id, synapse_id, origin_id, origin_type,
    anchor_event_id, contributor_ids, derived_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateEventDerivationParams struct {
	DerivedEventID uuid.UUID   `json:"derived_event_id"`
	SynapseID      string      `json:"synapse_id"`
	OriginID       string      `json:"origin_id"`
	OriginType     string      `json:"origin_type"`
	AnchorEventID  pgtype.UUID `json:"anchor_event_id"`
	ContributorIds []uuid.UUID `json:"contributor_ids"`
	DerivedAt      time.Time   `json:"derived_at"`
}

// ===========================================
// Event Derivations CRUD
// Maps to: materializeDerived() / materializeFromTemplate()
//
//	in synapse_runtime.go
//
// ===========================================
func (q *Queries) CreateEventDerivation(ctx context.Context, arg CreateEventDerivationParams) error {
	_, err := q.db.Exec(ctx, createEventDerivation,
		arg.DerivedEventID,
		arg.SynapseID,
		arg.OriginID,
		arg.OriginType,
		arg.AnchorEventID,
		arg.ContributorIds,
		arg.DerivedAt,
	)
	return err
}

const deleteEventDerivation = `-- name: DeleteEventDerivation :exec
DELETE FROM event_derivations WHERE derived_event_id = $1
`

func (q *Queries) DeleteEventDerivation(ctx context.Context, derivedEventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventDerivation, derivedEventID)
	return err
}

const getAllDerivationsBySynapse = `-- name: GetAllDerivationsBySynapse :many
SELECT derived_event_id, synapse_id, origin_id, origin_type, anchor_event_id, contributor_ids, derived_at FROM event_derivations
WHERE synapse_id = $1
ORDER BY derived_at
`

func (q *Queries) GetAllDerivationsBySynapse(ctx context.Context, synapseID string) ([]EventDerivation, error) {
	rows, err := q.db.Query(ctx, getAllDerivationsBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDerivation{}
	for rows.Next() {
		var i EventDerivation
		if err := rows.Scan(
			&i.DerivedEventID,
			&i.SynapseID,
			&i.OriginID,
			&i.OriginType,
			&i.AnchorEventID,
			&i.ContributorIds,
			&i.DerivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDerivationsByAnchor = `-- name: GetDerivationsByAnchor :many
SELECT derived_event_id, synapse_id, origin_id, origin_type, anchor_event_id, contributor_ids, derived_at FROM event_derivations
WHERE anchor_event_id = $1
ORDER BY derived_at
`

func (q *Queries) GetDerivationsByAnchor(ctx context.Context, anchorEventID pgtype.UUID) ([]EventDerivation, error) {
	rows, err := q.db.Query(ctx, getDerivationsByAnchor, anchorEventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDerivation{}
	for rows.Next() {
		var i EventDerivation
		if err := rows.Scan(
			&i.DerivedEventID,
			&i.SynapseID,
			&i.OriginID,
			&i.OriginType,
			&i.AnchorEventID,
			&i.ContributorIds,
			&i.DerivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDerivationsByOrigin = `-- name: GetDerivationsByOrigin :many
SELECT derived_event_id, synapse_id, origin_id, origin_type, anchor_event_id, contributor_ids, derived_at FROM event_derivations
WHERE synapse_id = $1 AND origin_id = $2
ORDER BY derived_at
`

type GetDerivationsByOriginParams struct {
	SynapseID string `json:"synapse_id"`
	OriginID  string `json:"origin_id"`
}

func (q *Queries) GetDerivationsByOrigin(ctx context.Context, arg GetDerivationsByOriginParams) ([]EventDerivation, error) {
	rows, err := q.db.Query(ctx, getDerivationsByOrigin, arg.SynapseID, arg.OriginID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDerivation{}
	for rows.Next() {
		var i EventDerivation
		if err := rows.Scan(
			&i.DerivedEventID,
			&i.SynapseID,
			&i.OriginID,
			&i.OriginType,
			&i.AnchorEventID,
			&i.ContributorIds,
			&i.DerivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDerivationsBySynapse = `-- name: GetDerivationsBySynapse :many
SELECT derived_event_id, synapse_id, origin_id, origin_type, anchor_event_id, contributor_ids, derived_at FROM event_derivations
WHERE synapse_id = $1
ORDER BY derived_at
LIMIT $2 OFFSET $3
`

type GetDerivationsBySynapseParams struct {
	SynapseID string `json:"synapse_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) GetDerivationsBySynapse(ctx context.Context, arg GetDerivationsBySynapseParams) ([]EventDerivation, error) {
	rows, err := q.db.Query(ctx, getDerivationsBySynapse, arg.SynapseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventDerivation{}
	for rows.Next() {
		var i EventDerivation
		if err := rows.Scan(
			&i.DerivedEventID,
			&i.SynapseID,
			&i.OriginID,
			&i.OriginType,
			&i.AnchorEventID,
			&i.ContributorIds,
			&i.DerivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventDerivation = `-- name: GetEventDerivation :one
SELECT derived_event_id, synapse_id, origin_id, origin_type, anchor_event_id, contributor_ids, derived_at FROM event_derivations WHERE derived_event_id = $1
`

func (q *Queries) GetEventDerivation(ctx context.Context, derivedEventID uuid.UUID) (EventDerivation, error) {
	row := q.db.QueryRow(ctx, getEventDerivation, derivedEventID)
	var i EventDerivation
	err := row.Scan(
		&i.DerivedEventID,
		&i.SynapseID,
		&i.OriginID,
		&i.OriginType,
		&i.AnchorEventID,
		&i.ContributorIds,
		&i.DerivedAt,
	)
	return i, err
}
