// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events WHERE synapse_id = $1
`

func (q *Queries) CountEvents(ctx context.Context, synapseID string) (int64, error) {
	row := q.db.QueryRow(ctx, countEvents, synapseID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByOrigin = `-- name: CountEventsByOrigin :one
SELECT count(*) FROM events WHERE synapse_id = $1 AND origin = $2
`

type CountEventsByOriginParams struct {
	SynapseID string `json:"synapse_id"`
	Origin    string `json:"origin"`
}

func (q *Queries) CountEventsByOrigin(ctx context.Context, arg CountEventsByOriginParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEventsByOrigin, arg.SynapseID, arg.Origin)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one

INSERT INTO events (id, synapse_id, event_type, event_domain, properties, timestamp, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at
`

type CreateEventParams struct {
	ID          uuid.UUID       `json:"id"`
	SynapseID   string          `json:"synapse_id"`
	EventType   string          `json:"event_type"`
	EventDomain string          `json:"event_domain"`
	Properties  json.RawMessage `json:"properties"`
	Timestamp   time.Time       `json:"timestamp"`
	Origin      string          `json:"origin"`
}

// ===========================================
// Events CRUD
// Maps to: Event (event.go)
// ===========================================
func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.ID,
		arg.SynapseID,
		arg.EventType,
		arg.EventDomain,
		arg.Properties,
		arg.Timestamp,
		arg.Origin,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.EventType,
		&i.EventDomain,
		&i.Properties,
		&i.Timestamp,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getAllEventsBySynapse = `-- name: GetAllEventsBySynapse :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events
WHERE synapse_id = $1
ORDER BY timestamp
`

func (q *Queries) GetAllEventsBySynapse(ctx context.Context, synapseID string) ([]Event, error) {
	rows, err := q.db.Query(ctx, getAllEventsBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.EventType,
		&i.EventDomain,
		&i.Properties,
		&i.Timestamp,
		&i.Origin,
		&i.CreatedAt,
	)
	return i, err
}

const getEventsByIDs = `-- name: GetEventsByIDs :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetEventsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByOrigin = `-- name: GetEventsByOrigin :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events
WHERE synapse_id = $1 AND origin = $2
ORDER BY timestamp
`

type GetEventsByOriginParams struct {
	SynapseID string `json:"synapse_id"`
	Origin    string `json:"origin"`
}

func (q *Queries) GetEventsByOrigin(ctx context.Context, arg GetEventsByOriginParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByOrigin, arg.SynapseID, arg.Origin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsBySynapse = `-- name: GetEventsBySynapse :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events
WHERE synapse_id = $1
ORDER BY timestamp
LIMIT $2 OFFSET $3
`

type GetEventsBySynapseParams struct {
	SynapseID string `json:"synapse_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) GetEventsBySynapse(ctx context.Context, arg GetEventsBySynapseParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsBySynapse, arg.SynapseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByType = `-- name: GetEventsByType :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events
WHERE synapse_id = $1 AND event_type = $2
ORDER BY timestamp
`

type GetEventsByTypeParams struct {
	SynapseID string `json:"synapse_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByType, arg.SynapseID, arg.EventType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEventsByTypeAndDomain = `-- name: GetEventsByTypeAndDomain :many
SELECT id, synapse_id, event_type, event_domain, properties, timestamp, origin, created_at FROM events
WHERE synapse_id = $1 AND event_type = $2 AND event_domain = $3
ORDER BY timestamp
`

type GetEventsByTypeAndDomainParams struct {
	SynapseID   string `json:"synapse_id"`
	EventType   string `json:"event_type"`
	EventDomain string `json:"event_domain"`
}

func (q *Queries) GetEventsByTypeAndDomain(ctx context.Context, arg GetEventsByTypeAndDomainParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getEventsByTypeAndDomain, arg.SynapseID, arg.EventType, arg.EventDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.EventType,
			&i.EventDomain,
			&i.Properties,
			&i.Timestamp,
			&i.Origin,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
