// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lineage.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLineageSamples = `-- name: CountLineageSamples :one
SELECT count(*) FROM lineage_samples
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type CountLineageSamplesParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) CountLineageSamples(ctx context.Context, arg CountLineageSamplesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLineageSamples,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLineageSample = `-- name: CreateLineageSample :one

INSERT INTO lineage_samples (
    synapse_id, derived_type, derived_domain, depth, sig,
    at, rule_id, derived_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, synapse_id, derived_type, derived_domain, depth, sig, at, rule_id, derived_id
`

type CreateLineageSampleParams struct {
	SynapseID     string    `json:"synapse_id"`
	DerivedType   string    `json:"derived_type"`
	DerivedDomain string    `json:"derived_domain"`
	Depth         int32     `json:"depth"`
	Sig           int64     `json:"sig"`
	At            time.Time `json:"at"`
	RuleID        string    `json:"rule_id"`
	DerivedID     uuid.UUID `json:"derived_id"`
}

// ---- Lineage samples ----
func (q *Queries) CreateLineageSample(ctx context.Context, arg CreateLineageSampleParams) (LineageSample, error) {
	row := q.db.QueryRow(ctx, createLineageSample,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
		arg.At,
		arg.RuleID,
		arg.DerivedID,
	)
	var i LineageSample
	err := row.Scan(
		&i.ID,
		&i.SynapseID,
		&i.DerivedType,
		&i.DerivedDomain,
		&i.Depth,
		&i.Sig,
		&i.At,
		&i.RuleID,
		&i.DerivedID,
	)
	return i, err
}

const deleteLineageRuleCounts = `-- name: DeleteLineageRuleCounts :exec
DELETE FROM lineage_rule_counts
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type DeleteLineageRuleCountsParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) DeleteLineageRuleCounts(ctx context.Context, arg DeleteLineageRuleCountsParams) error {
	_, err := q.db.Exec(ctx, deleteLineageRuleCounts,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	return err
}

const deleteLineageSamples = `-- name: DeleteLineageSamples :exec
DELETE FROM lineage_samples
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type DeleteLineageSamplesParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) DeleteLineageSamples(ctx context.Context, arg DeleteLineageSamplesParams) error {
	_, err := q.db.Exec(ctx, deleteLineageSamples,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	return err
}

const deleteLineageStats = `-- name: DeleteLineageStats :exec
DELETE FROM lineage_stats
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type DeleteLineageStatsParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) DeleteLineageStats(ctx context.Context, arg DeleteLineageStatsParams) error {
	_, err := q.db.Exec(ctx, deleteLineageStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	return err
}

const getAllLineageRuleCountsBySynapse = `-- name: GetAllLineageRuleCountsBySynapse :many
SELECT synapse_id, derived_type, derived_domain, depth, sig, rule_id, count FROM lineage_rule_counts
WHERE synapse_id = $1
`

func (q *Queries) GetAllLineageRuleCountsBySynapse(ctx context.Context, synapseID string) ([]LineageRuleCount, error) {
	rows, err := q.db.Query(ctx, getAllLineageRuleCountsBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageRuleCount{}
	for rows.Next() {
		var i LineageRuleCount
		if err := rows.Scan(
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.RuleID,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLineageSamplesBySynapse = `-- name: GetAllLineageSamplesBySynapse :many
SELECT id, synapse_id, derived_type, derived_domain, depth, sig, at, rule_id, derived_id FROM lineage_samples
WHERE synapse_id = $1
ORDER BY at DESC
`

func (q *Queries) GetAllLineageSamplesBySynapse(ctx context.Context, synapseID string) ([]LineageSample, error) {
	rows, err := q.db.Query(ctx, getAllLineageSamplesBySynapse, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageSample{}
	for rows.Next() {
		var i LineageSample
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.At,
			&i.RuleID,
			&i.DerivedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllLineageStats = `-- name: GetAllLineageStats :many
SELECT synapse_id, derived_type, derived_domain, depth, sig, count, last_seen FROM lineage_stats
WHERE synapse_id = $1
ORDER BY last_seen DESC
`

func (q *Queries) GetAllLineageStats(ctx context.Context, synapseID string) ([]LineageStat, error) {
	rows, err := q.db.Query(ctx, getAllLineageStats, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageStat{}
	for rows.Next() {
		var i LineageStat
		if err := rows.Scan(
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.Count,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLineageRuleCounts = `-- name: GetLineageRuleCounts :many
SELECT synapse_id, derived_type, derived_domain, depth, sig, rule_id, count FROM lineage_rule_counts
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type GetLineageRuleCountsParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) GetLineageRuleCounts(ctx context.Context, arg GetLineageRuleCountsParams) ([]LineageRuleCount, error) {
	rows, err := q.db.Query(ctx, getLineageRuleCounts,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageRuleCount{}
	for rows.Next() {
		var i LineageRuleCount
		if err := rows.Scan(
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.RuleID,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLineageSamples = `-- name: GetLineageSamples :many
SELECT id, synapse_id, derived_type, derived_domain, depth, sig, at, rule_id, derived_id FROM lineage_samples
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
ORDER BY at DESC
`

type GetLineageSamplesParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) GetLineageSamples(ctx context.Context, arg GetLineageSamplesParams) ([]LineageSample, error) {
	rows, err := q.db.Query(ctx, getLineageSamples,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageSample{}
	for rows.Next() {
		var i LineageSample
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.At,
			&i.RuleID,
			&i.DerivedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLineageStats = `-- name: GetLineageStats :one
SELECT synapse_id, derived_type, derived_domain, depth, sig, count, last_seen FROM lineage_stats
WHERE synapse_id     = $1
  AND derived_type   = $2
  AND derived_domain = $3
  AND depth          = $4
  AND sig            = $5
`

type GetLineageStatsParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
}

func (q *Queries) GetLineageStats(ctx context.Context, arg GetLineageStatsParams) (LineageStat, error) {
	row := q.db.QueryRow(ctx, getLineageStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
	)
	var i LineageStat
	err := row.Scan(
		&i.SynapseID,
		&i.DerivedType,
		&i.DerivedDomain,
		&i.Depth,
		&i.Sig,
		&i.Count,
		&i.LastSeen,
	)
	return i, err
}

const incrementLineageRuleCount = `-- name: IncrementLineageRuleCount :exec

INSERT INTO lineage_rule_counts (synapse_id, derived_type, derived_domain, depth, sig, rule_id, count)
VALUES ($1, $2, $3, $4, $5, $6, 1)
ON CONFLICT (synapse_id, derived_type, derived_domain, depth, sig, rule_id) DO UPDATE
    SET count = lineage_rule_counts.count + 1
`

type IncrementLineageRuleCountParams struct {
	SynapseID     string `json:"synapse_id"`
	DerivedType   string `json:"derived_type"`
	DerivedDomain string `json:"derived_domain"`
	Depth         int32  `json:"depth"`
	Sig           int64  `json:"sig"`
	RuleID        string `json:"rule_id"`
}

// ---- Lineage rule counts ----
func (q *Queries) IncrementLineageRuleCount(ctx context.Context, arg IncrementLineageRuleCountParams) error {
	_, err := q.db.Exec(ctx, incrementLineageRuleCount,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
		arg.RuleID,
	)
	return err
}

const incrementLineageStats = `-- name: IncrementLineageStats :exec


INSERT INTO lineage_stats (synapse_id, derived_type, derived_domain, depth, sig, count, last_seen)
VALUES ($1, $2, $3, $4, $5, 1, $6)
ON CONFLICT (synapse_id, derived_type, derived_domain, depth, sig) DO UPDATE
    SET count     = lineage_stats.count + 1,
        last_seen = EXCLUDED.last_seen
`

type IncrementLineageStatsParams struct {
	SynapseID     string    `json:"synapse_id"`
	DerivedType   string    `json:"derived_type"`
	DerivedDomain string    `json:"derived_domain"`
	Depth         int32     `json:"depth"`
	Sig           int64     `json:"sig"`
	LastSeen      time.Time `json:"last_seen"`
}

// ===========================================
// Lineage Stats, Rule Counts & Samples CRUD
// Maps to: lineageStats map[LineageKey]*LineageStats
//
//	in InMemoryStructuralMemory
//
// ===========================================
// ---- Lineage stats ----
func (q *Queries) IncrementLineageStats(ctx context.Context, arg IncrementLineageStatsParams) error {
	_, err := q.db.Exec(ctx, incrementLineageStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
		arg.LastSeen,
	)
	return err
}

const listLineageStats = `-- name: ListLineageStats :many
SELECT synapse_id, derived_type, derived_domain, depth, sig, count, last_seen FROM lineage_stats
WHERE synapse_id = $1
ORDER BY last_seen DESC
LIMIT $2 OFFSET $3
`

type ListLineageStatsParams struct {
	SynapseID string `json:"synapse_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListLineageStats(ctx context.Context, arg ListLineageStatsParams) ([]LineageStat, error) {
	rows, err := q.db.Query(ctx, listLineageStats, arg.SynapseID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LineageStat{}
	for rows.Next() {
		var i LineageStat
		if err := rows.Scan(
			&i.SynapseID,
			&i.DerivedType,
			&i.DerivedDomain,
			&i.Depth,
			&i.Sig,
			&i.Count,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLineageStats = `-- name: UpsertLineageStats :exec
INSERT INTO lineage_stats (synapse_id, derived_type, derived_domain, depth, sig, count, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (synapse_id, derived_type, derived_domain, depth, sig) DO UPDATE
    SET count     = EXCLUDED.count,
        last_seen = EXCLUDED.last_seen
`

type UpsertLineageStatsParams struct {
	SynapseID     string    `json:"synapse_id"`
	DerivedType   string    `json:"derived_type"`
	DerivedDomain string    `json:"derived_domain"`
	Depth         int32     `json:"depth"`
	Sig           int64     `json:"sig"`
	Count         int32     `json:"count"`
	LastSeen      time.Time `json:"last_seen"`
}

func (q *Queries) UpsertLineageStats(ctx context.Context, arg UpsertLineageStatsParams) error {
	_, err := q.db.Exec(ctx, upsertLineageStats,
		arg.SynapseID,
		arg.DerivedType,
		arg.DerivedDomain,
		arg.Depth,
		arg.Sig,
		arg.Count,
		arg.LastSeen,
	)
	return err
}
