// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ---- Required patterns per composition ----
	// Maps to: PatternCompositionSpec.RequiredPatterns and MinOccurrences
	AddCompositionRequiredPattern(ctx context.Context, arg AddCompositionRequiredPatternParams) error
	// ---- Rule <-> EventType bindings ----
	// Maps to: RegisterRule / RegisterRuleForTypes
	AddRuleEventType(ctx context.Context, arg AddRuleEventTypeParams) error
	CountDerivationsBySynapse(ctx context.Context, synapseID string) (int64, error)
	CountEvents(ctx context.Context, synapseID string) (int64, error)
	CountEventsByOrigin(ctx context.Context, arg CountEventsByOriginParams) (int64, error)
	CountLineageSamples(ctx context.Context, arg CountLineageSamplesParams) (int64, error)
	CountMotifInstances(ctx context.Context, arg CountMotifInstancesParams) (int64, error)
	// ---- Composition match log ----
	CreateCompositionMatchLog(ctx context.Context, arg CreateCompositionMatchLogParams) (CompositionMatchLog, error)
	// ===========================================
	// Composition Specs & Required Patterns CRUD
	// Maps to: PatternCompositionSpec (pattern_composition.go)
	//      and PatternIdentifier
	// ===========================================
	// ---- Composition specs ----
	CreateCompositionSpec(ctx context.Context, arg CreateCompositionSpecParams) (CompositionSpec, error)
	// ===========================================
	// Edges CRUD
	// Maps to: Edge (edge.go)
	// ===========================================
	CreateEdge(ctx context.Context, arg CreateEdgeParams) error
	// ===========================================
	// Events CRUD
	// Maps to: Event (event.go)
	// ===========================================
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// ===========================================
	// Event Derivations CRUD
	// Maps to: materializeDerived() / materializeFromTemplate()
	//          in synapse_runtime.go
	// ===========================================
	CreateEventDerivation(ctx context.Context, arg CreateEventDerivationParams) error
	// ---- Lineage samples ----
	CreateLineageSample(ctx context.Context, arg CreateLineageSampleParams) (LineageSample, error)
	// ---- Motif instances ----
	CreateMotifInstance(ctx context.Context, arg CreateMotifInstanceParams) (MotifInstance, error)
	// ===========================================
	// Audit / Logging CRUD
	// Maps to: PatternMatch (pattern_watcher.go)
	//      and PatternCompositionMatch (pattern_composition.go)
	// ===========================================
	// ---- Pattern match log ----
	CreatePatternMatchLog(ctx context.Context, arg CreatePatternMatchLogParams) (PatternMatchLog, error)
	// ===========================================
	// Pattern Watcher Configs CRUD
	// Maps to: PatternWatcher / PatternConfig (pattern_watcher.go)
	//      and WatchSpec (pattern_watcher.go)
	// ===========================================
	CreatePatternWatcherConfig(ctx context.Context, arg CreatePatternWatcherConfigParams) (PatternWatcherConfig, error)
	// ===========================================
	// Rules & Rule-EventType Bindings CRUD
	// Maps to: DeriveEventRule (rules.go)
	//      and SynapseRuntime.rulesByType (synapse_runtime.go)
	// ===========================================
	// ---- Rules ----
	CreateRule(ctx context.Context, arg CreateRuleParams) (Rule, error)
	// ===========================================
	// Synapse Instances CRUD
	// Maps to: SynapseRuntime (synapse_runtime.go)
	// ===========================================
	CreateSynapseInstance(ctx context.Context, arg CreateSynapseInstanceParams) (SynapseInstance, error)
	// ===========================================
	// Watcher → Composition Wiring CRUD
	// Maps to: CompositePatternListener.watchers
	//          in pattern_composition.go
	// ===========================================
	CreateWatcherCompositionLink(ctx context.Context, arg CreateWatcherCompositionLinkParams) error
	DeleteCompositionMatchLog(ctx context.Context, id int64) error
	DeleteCompositionRequiredPattern(ctx context.Context, arg DeleteCompositionRequiredPatternParams) error
	DeleteCompositionRequiredPatterns(ctx context.Context, compositionID string) error
	DeleteCompositionSpec(ctx context.Context, compositionID string) error
	DeleteEdge(ctx context.Context, arg DeleteEdgeParams) error
	DeleteEdgesFrom(ctx context.Context, fromEventID uuid.UUID) error
	DeleteEdgesTo(ctx context.Context, toEventID uuid.UUID) error
	DeleteEvent(ctx context.Context, id uuid.UUID) error
	DeleteEventDerivation(ctx context.Context, derivedEventID uuid.UUID) error
	DeleteEventRevision(ctx context.Context, eventID uuid.UUID) error
	DeleteEventSignatures(ctx context.Context, eventID uuid.UUID) error
	DeleteLineageRuleCounts(ctx context.Context, arg DeleteLineageRuleCountsParams) error
	DeleteLineageSamples(ctx context.Context, arg DeleteLineageSamplesParams) error
	DeleteLineageStats(ctx context.Context, arg DeleteLineageStatsParams) error
	DeleteMotifInstances(ctx context.Context, arg DeleteMotifInstancesParams) error
	DeleteMotifStats(ctx context.Context, arg DeleteMotifStatsParams) error
	DeletePatternMatchLog(ctx context.Context, id int64) error
	DeletePatternWatcherConfig(ctx context.Context, id string) error
	DeleteRule(ctx context.Context, id string) error
	DeleteRuleEventType(ctx context.Context, arg DeleteRuleEventTypeParams) error
	DeleteRuleEventTypes(ctx context.Context, ruleID string) error
	DeleteSynapseInstance(ctx context.Context, id string) error
	DeleteTypeRevision(ctx context.Context, arg DeleteTypeRevisionParams) error
	DeleteWatcherCompositionLink(ctx context.Context, arg DeleteWatcherCompositionLinkParams) error
	DeleteWatcherCompositionLinksByComposition(ctx context.Context, compositionID string) error
	DeleteWatcherCompositionLinksByWatcher(ctx context.Context, patternWatcherID string) error
	GetAllDerivationsBySynapse(ctx context.Context, synapseID string) ([]EventDerivation, error)
	GetAllEventsBySynapse(ctx context.Context, synapseID string) ([]Event, error)
	GetAllLineageRuleCountsBySynapse(ctx context.Context, synapseID string) ([]LineageRuleCount, error)
	GetAllLineageSamplesBySynapse(ctx context.Context, synapseID string) ([]LineageSample, error)
	GetAllLineageStats(ctx context.Context, synapseID string) ([]LineageStat, error)
	GetAllMotifInstancesBySynapse(ctx context.Context, synapseID string) ([]MotifInstance, error)
	GetCompositionRequiredPatterns(ctx context.Context, compositionID string) ([]CompositionRequiredPattern, error)
	GetCompositionSpec(ctx context.Context, compositionID string) (CompositionSpec, error)
	GetCompositionsByWatcher(ctx context.Context, patternWatcherID string) ([]CompositionSpec, error)
	GetDerivationsByAnchor(ctx context.Context, anchorEventID pgtype.UUID) ([]EventDerivation, error)
	GetDerivationsByOrigin(ctx context.Context, arg GetDerivationsByOriginParams) ([]EventDerivation, error)
	GetDerivationsBySynapse(ctx context.Context, arg GetDerivationsBySynapseParams) ([]EventDerivation, error)
	GetEdge(ctx context.Context, arg GetEdgeParams) (Edge, error)
	GetEdgesBySynapse(ctx context.Context, synapseID string) ([]Edge, error)
	GetEdgesFrom(ctx context.Context, fromEventID uuid.UUID) ([]Edge, error)
	GetEdgesTo(ctx context.Context, toEventID uuid.UUID) ([]Edge, error)
	GetEventByID(ctx context.Context, id uuid.UUID) (Event, error)
	GetEventDerivation(ctx context.Context, derivedEventID uuid.UUID) (EventDerivation, error)
	// ---- Per-event revisions (in_rev / out_rev) ----
	GetEventRevision(ctx context.Context, eventID uuid.UUID) (RevisionByEvent, error)
	GetEventSignature(ctx context.Context, arg GetEventSignatureParams) (EventSignature, error)
	GetEventSignatures(ctx context.Context, eventID uuid.UUID) ([]EventSignature, error)
	GetEventsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]Event, error)
	GetEventsByOrigin(ctx context.Context, arg GetEventsByOriginParams) ([]Event, error)
	GetEventsBySynapse(ctx context.Context, arg GetEventsBySynapseParams) ([]Event, error)
	GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]Event, error)
	GetEventsByTypeAndDomain(ctx context.Context, arg GetEventsByTypeAndDomainParams) ([]Event, error)
	GetGlobalRevision(ctx context.Context, synapseID string) (int64, error)
	GetLineageRuleCounts(ctx context.Context, arg GetLineageRuleCountsParams) ([]LineageRuleCount, error)
	GetLineageSamples(ctx context.Context, arg GetLineageSamplesParams) ([]LineageSample, error)
	GetLineageStats(ctx context.Context, arg GetLineageStatsParams) (LineageStat, error)
	GetMotifInstances(ctx context.Context, arg GetMotifInstancesParams) ([]MotifInstance, error)
	GetMotifStats(ctx context.Context, arg GetMotifStatsParams) (MotifStat, error)
	GetPatternMatchLogsByDerivedID(ctx context.Context, derivedID uuid.UUID) ([]PatternMatchLog, error)
	GetPatternWatcherConfig(ctx context.Context, id string) (PatternWatcherConfig, error)
	GetRule(ctx context.Context, id string) (Rule, error)
	GetRuleEventTypes(ctx context.Context, ruleID string) ([]RuleEventType, error)
	GetRulesByEventType(ctx context.Context, arg GetRulesByEventTypeParams) ([]Rule, error)
	GetSignaturesBySynapse(ctx context.Context, synapseID string) ([]EventSignature, error)
	GetSynapseInstance(ctx context.Context, id string) (SynapseInstance, error)
	// ---- Per-type revisions (per synapse) ----
	GetTypeRevision(ctx context.Context, arg GetTypeRevisionParams) (RevisionByType, error)
	GetWatchersByComposition(ctx context.Context, compositionID string) ([]PatternWatcherConfig, error)
	IncrementEventInRev(ctx context.Context, arg IncrementEventInRevParams) error
	IncrementEventOutRev(ctx context.Context, arg IncrementEventOutRevParams) error
	IncrementGlobalRevision(ctx context.Context, synapseID string) (int64, error)
	// ---- Lineage rule counts ----
	IncrementLineageRuleCount(ctx context.Context, arg IncrementLineageRuleCountParams) error
	// ===========================================
	// Lineage Stats, Rule Counts & Samples CRUD
	// Maps to: lineageStats map[LineageKey]*LineageStats
	//          in InMemoryStructuralMemory
	// ===========================================
	// ---- Lineage stats ----
	IncrementLineageStats(ctx context.Context, arg IncrementLineageStatsParams) error
	// ===========================================
	// Motif Stats & Instances CRUD
	// Maps to: motifs map[MotifKey]*MotifStats
	//          in InMemoryStructuralMemory
	// ===========================================
	// ---- Motif stats ----
	IncrementMotifStats(ctx context.Context, arg IncrementMotifStatsParams) error
	IncrementTypeRevision(ctx context.Context, arg IncrementTypeRevisionParams) error
	// ===========================================
	// Revision Counters CRUD
	// Maps to: global, inRev, outRev, typeRev
	//          in InMemoryStructuralMemory
	// ===========================================
	// ---- Global revision (per synapse) ----
	InitGlobalRevision(ctx context.Context, synapseID string) error
	ListCompositionMatchLogs(ctx context.Context, arg ListCompositionMatchLogsParams) ([]CompositionMatchLog, error)
	ListCompositionMatchLogsBySpec(ctx context.Context, arg ListCompositionMatchLogsBySpecParams) ([]CompositionMatchLog, error)
	ListCompositionSpecs(ctx context.Context, synapseID string) ([]CompositionSpec, error)
	ListEventRevisions(ctx context.Context, synapseID string) ([]RevisionByEvent, error)
	ListLineageStats(ctx context.Context, arg ListLineageStatsParams) ([]LineageStat, error)
	ListMotifStats(ctx context.Context, synapseID string) ([]MotifStat, error)
	ListPatternMatchLogs(ctx context.Context, arg ListPatternMatchLogsParams) ([]PatternMatchLog, error)
	ListPatternMatchLogsByType(ctx context.Context, arg ListPatternMatchLogsByTypeParams) ([]PatternMatchLog, error)
	ListPatternWatcherConfigs(ctx context.Context, synapseID string) ([]PatternWatcherConfig, error)
	ListRuleEventTypesBySynapse(ctx context.Context, synapseID string) ([]RuleEventType, error)
	ListRules(ctx context.Context, synapseID string) ([]Rule, error)
	ListSynapseInstances(ctx context.Context) ([]SynapseInstance, error)
	ListTypeRevisions(ctx context.Context, synapseID string) ([]RevisionByType, error)
	ListWatcherCompositionLinks(ctx context.Context, synapseID string) ([]WatcherCompositionLink, error)
	UpdateCompositionSpec(ctx context.Context, arg UpdateCompositionSpecParams) error
	UpdatePatternWatcherConfig(ctx context.Context, arg UpdatePatternWatcherConfigParams) error
	UpdateRule(ctx context.Context, arg UpdateRuleParams) error
	UpdateSynapseInstance(ctx context.Context, arg UpdateSynapseInstanceParams) error
	// ===========================================
	// Event Signatures CRUD
	// Maps to: sigs map[EventID][]uint64
	//          in InMemoryStructuralMemory
	// ===========================================
	UpsertEventSignature(ctx context.Context, arg UpsertEventSignatureParams) error
	UpsertLineageStats(ctx context.Context, arg UpsertLineageStatsParams) error
	UpsertMotifStats(ctx context.Context, arg UpsertMotifStatsParams) error
}

var _ Querier = (*Queries)(nil)
