// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revisions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const deleteEventRevision = `-- name: DeleteEventRevision :exec
DELETE FROM revision_by_event WHERE event_id = $1
`

func (q *Queries) DeleteEventRevision(ctx context.Context, eventID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventRevision, eventID)
	return err
}

const deleteTypeRevision = `-- name: DeleteTypeRevision :exec
DELETE FROM revision_by_type WHERE synapse_id = $1 AND event_type = $2
`

type DeleteTypeRevisionParams struct {
	SynapseID string `json:"synapse_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) DeleteTypeRevision(ctx context.Context, arg DeleteTypeRevisionParams) error {
	_, err := q.db.Exec(ctx, deleteTypeRevision, arg.SynapseID, arg.EventType)
	return err
}

const getEventRevision = `-- name: GetEventRevision :one

SELECT event_id, synapse_id, in_rev, out_rev FROM revision_by_event WHERE event_id = $1
`

// ---- Per-event revisions (in_rev / out_rev) ----
func (q *Queries) GetEventRevision(ctx context.Context, eventID uuid.UUID) (RevisionByEvent, error) {
	row := q.db.QueryRow(ctx, getEventRevision, eventID)
	var i RevisionByEvent
	err := row.Scan(
		&i.EventID,
		&i.SynapseID,
		&i.InRev,
		&i.OutRev,
	)
	return i, err
}

const getGlobalRevision = `-- name: GetGlobalRevision :one
SELECT revision FROM revision_global WHERE synapse_id = $1
`

func (q *Queries) GetGlobalRevision(ctx context.Context, synapseID string) (int64, error) {
	row := q.db.QueryRow(ctx, getGlobalRevision, synapseID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getTypeRevision = `-- name: GetTypeRevision :one

SELECT synapse_id, event_type, type_rev FROM revision_by_type WHERE synapse_id = $1 AND event_type = $2
`

type GetTypeRevisionParams struct {
	SynapseID string `json:"synapse_id"`
	EventType string `json:"event_type"`
}

// ---- Per-type revisions (per synapse) ----
func (q *Queries) GetTypeRevision(ctx context.Context, arg GetTypeRevisionParams) (RevisionByType, error) {
	row := q.db.QueryRow(ctx, getTypeRevision, arg.SynapseID, arg.EventType)
	var i RevisionByType
	err := row.Scan(&i.SynapseID, &i.EventType, &i.TypeRev)
	return i, err
}

const incrementEventInRev = `-- name: IncrementEventInRev :exec
INSERT INTO revision_by_event (event_id, synapse_id, in_rev, out_rev)
VALUES ($1, $2, 1, 0)
ON CONFLICT (event_id) DO UPDATE
    SET in_rev = revision_by_event.in_rev + 1
`

type IncrementEventInRevParams struct {
	EventID   uuid.UUID `json:"event_id"`
	SynapseID string    `json:"synapse_id"`
}

func (q *Queries) IncrementEventInRev(ctx context.Context, arg IncrementEventInRevParams) error {
	_, err := q.db.Exec(ctx, incrementEventInRev, arg.EventID, arg.SynapseID)
	return err
}

const incrementEventOutRev = `-- name: IncrementEventOutRev :exec
INSERT INTO revision_by_event (event_id, synapse_id, in_rev, out_rev)
VALUES ($1, $2, 0, 1)
ON CONFLICT (event_id) DO UPDATE
    SET out_rev = revision_by_event.out_rev + 1
`

type IncrementEventOutRevParams struct {
	EventID   uuid.UUID `json:"event_id"`
	SynapseID string    `json:"synapse_id"`
}

func (q *Queries) IncrementEventOutRev(ctx context.Context, arg IncrementEventOutRevParams) error {
	_, err := q.db.Exec(ctx, incrementEventOutRev, arg.EventID, arg.SynapseID)
	return err
}

const incrementGlobalRevision = `-- name: IncrementGlobalRevision :one
UPDATE revision_global
SET revision = revision + 1
WHERE synapse_id = $1
RETURNING revision
`

func (q *Queries) IncrementGlobalRevision(ctx context.Context, synapseID string) (int64, error) {
	row := q.db.QueryRow(ctx, incrementGlobalRevision, synapseID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const incrementTypeRevision = `-- name: IncrementTypeRevision :exec
INSERT INTO revision_by_type (synapse_id, event_type, type_rev)
VALUES ($1, $2, 1)
ON CONFLICT (synapse_id, event_type) DO UPDATE
    SET type_rev = revision_by_type.type_rev + 1
`

type IncrementTypeRevisionParams struct {
	SynapseID string `json:"synapse_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) IncrementTypeRevision(ctx context.Context, arg IncrementTypeRevisionParams) error {
	_, err := q.db.Exec(ctx, incrementTypeRevision, arg.SynapseID, arg.EventType)
	return err
}

const initGlobalRevision = `-- name: InitGlobalRevision :exec


INSERT INTO revision_global (synapse_id, revision)
VALUES ($1, 0)
ON CONFLICT (synapse_id) DO NOTHING
`

// ===========================================
// Revision Counters CRUD
// Maps to: global, inRev, outRev, typeRev
//
//	in InMemoryStructuralMemory
//
// ===========================================
// ---- Global revision (per synapse) ----
func (q *Queries) InitGlobalRevision(ctx context.Context, synapseID string) error {
	_, err := q.db.Exec(ctx, initGlobalRevision, synapseID)
	return err
}

const listEventRevisions = `-- name: ListEventRevisions :many
SELECT event_id, synapse_id, in_rev, out_rev FROM revision_by_event WHERE synapse_id = $1
`

func (q *Queries) ListEventRevisions(ctx context.Context, synapseID string) ([]RevisionByEvent, error) {
	rows, err := q.db.Query(ctx, listEventRevisions, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionByEvent{}
	for rows.Next() {
		var i RevisionByEvent
		if err := rows.Scan(
			&i.EventID,
			&i.SynapseID,
			&i.InRev,
			&i.OutRev,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypeRevisions = `-- name: ListTypeRevisions :many
SELECT synapse_id, event_type, type_rev FROM revision_by_type WHERE synapse_id = $1
`

func (q *Queries) ListTypeRevisions(ctx context.Context, synapseID string) ([]RevisionByType, error) {
	rows, err := q.db.Query(ctx, listTypeRevisions, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevisionByType{}
	for rows.Next() {
		var i RevisionByType
		if err := rows.Scan(&i.SynapseID, &i.EventType, &i.TypeRev); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
