// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: synapse_instances.sql

package repository

import (
	"context"
)

const createSynapseInstance = `-- name: CreateSynapseInstance :one

INSERT INTO synapse_instances (id, description, max_depth, max_samples_per_lineage)
VALUES ($1, $2, $3, $4)
RETURNING id, description, max_depth, max_samples_per_lineage, created_at, updated_at
`

type CreateSynapseInstanceParams struct {
	ID                   string `json:"id"`
	Description          string `json:"description"`
	MaxDepth             int32  `json:"max_depth"`
	MaxSamplesPerLineage int32  `json:"max_samples_per_lineage"`
}

// ===========================================
// Synapse Instances CRUD
// Maps to: SynapseRuntime (synapse_runtime.go)
// ===========================================
func (q *Queries) CreateSynapseInstance(ctx context.Context, arg CreateSynapseInstanceParams) (SynapseInstance, error) {
	row := q.db.QueryRow(ctx, createSynapseInstance,
		arg.ID,
		arg.Description,
		arg.MaxDepth,
		arg.MaxSamplesPerLineage,
	)
	var i SynapseInstance
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.MaxDepth,
		&i.MaxSamplesPerLineage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSynapseInstance = `-- name: DeleteSynapseInstance :exec
DELETE FROM synapse_instances WHERE id = $1
`

func (q *Queries) DeleteSynapseInstance(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSynapseInstance, id)
	return err
}

const getSynapseInstance = `-- name: GetSynapseInstance :one
SELECT id, description, max_depth, max_samples_per_lineage, created_at, updated_at FROM synapse_instances WHERE id = $1
`

func (q *Queries) GetSynapseInstance(ctx context.Context, id string) (SynapseInstance, error) {
	row := q.db.QueryRow(ctx, getSynapseInstance, id)
	var i SynapseInstance
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.MaxDepth,
		&i.MaxSamplesPerLineage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSynapseInstances = `-- name: ListSynapseInstances :many
SELECT id, description, max_depth, max_samples_per_lineage, created_at, updated_at FROM synapse_instances ORDER BY created_at
`

func (q *Queries) ListSynapseInstances(ctx context.Context) ([]SynapseInstance, error) {
	rows, err := q.db.Query(ctx, listSynapseInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SynapseInstance{}
	for rows.Next() {
		var i SynapseInstance
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.MaxDepth,
			&i.MaxSamplesPerLineage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSynapseInstance = `-- name: UpdateSynapseInstance :exec
UPDATE synapse_instances SET
    description             = $2,
    max_depth               = $3,
    max_samples_per_lineage = $4,
    updated_at              = now()
WHERE id = $1
`

type UpdateSynapseInstanceParams struct {
	ID                   string `json:"id"`
	Description          string `json:"description"`
	MaxDepth             int32  `json:"max_depth"`
	MaxSamplesPerLineage int32  `json:"max_samples_per_lineage"`
}

func (q *Queries) UpdateSynapseInstance(ctx context.Context, arg UpdateSynapseInstanceParams) error {
	_, err := q.db.Exec(ctx, updateSynapseInstance,
		arg.ID,
		arg.Description,
		arg.MaxDepth,
		arg.MaxSamplesPerLineage,
	)
	return err
}
