// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: watcher_links.sql

package repository

import (
	"context"
)

const createWatcherCompositionLink = `-- name: CreateWatcherCompositionLink :exec

INSERT INTO watcher_composition_links (pattern_watcher_id, composition_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateWatcherCompositionLinkParams struct {
	PatternWatcherID string `json:"pattern_watcher_id"`
	CompositionID    string `json:"composition_id"`
}

// ===========================================
// Watcher → Composition Wiring CRUD
// Maps to: CompositePatternListener.watchers
//
//	in pattern_composition.go
//
// ===========================================
func (q *Queries) CreateWatcherCompositionLink(ctx context.Context, arg CreateWatcherCompositionLinkParams) error {
	_, err := q.db.Exec(ctx, createWatcherCompositionLink, arg.PatternWatcherID, arg.CompositionID)
	return err
}

const deleteWatcherCompositionLink = `-- name: DeleteWatcherCompositionLink :exec
DELETE FROM watcher_composition_links
WHERE pattern_watcher_id = $1 AND composition_id = $2
`

type DeleteWatcherCompositionLinkParams struct {
	PatternWatcherID string `json:"pattern_watcher_id"`
	CompositionID    string `json:"composition_id"`
}

func (q *Queries) DeleteWatcherCompositionLink(ctx context.Context, arg DeleteWatcherCompositionLinkParams) error {
	_, err := q.db.Exec(ctx, deleteWatcherCompositionLink, arg.PatternWatcherID, arg.CompositionID)
	return err
}

const deleteWatcherCompositionLinksByComposition = `-- name: DeleteWatcherCompositionLinksByComposition :exec
DELETE FROM watcher_composition_links
WHERE composition_id = $1
`

func (q *Queries) DeleteWatcherCompositionLinksByComposition(ctx context.Context, compositionID string) error {
	_, err := q.db.Exec(ctx, deleteWatcherCompositionLinksByComposition, compositionID)
	return err
}

const deleteWatcherCompositionLinksByWatcher = `-- name: DeleteWatcherCompositionLinksByWatcher :exec
DELETE FROM watcher_composition_links
WHERE pattern_watcher_id = $1
`

func (q *Queries) DeleteWatcherCompositionLinksByWatcher(ctx context.Context, patternWatcherID string) error {
	_, err := q.db.Exec(ctx, deleteWatcherCompositionLinksByWatcher, patternWatcherID)
	return err
}

const getCompositionsByWatcher = `-- name: GetCompositionsByWatcher :many
SELECT cs.composition_id, cs.synapse_id, cs.time_window_within, cs.time_window_unit, cs.derived_template_type, cs.derived_template_domain, cs.derived_template_props, cs.created_at
FROM composition_specs cs
JOIN watcher_composition_links wcl ON cs.composition_id = wcl.composition_id
WHERE wcl.pattern_watcher_id = $1
`

func (q *Queries) GetCompositionsByWatcher(ctx context.Context, patternWatcherID string) ([]CompositionSpec, error) {
	rows, err := q.db.Query(ctx, getCompositionsByWatcher, patternWatcherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CompositionSpec{}
	for rows.Next() {
		var i CompositionSpec
		if err := rows.Scan(
			&i.CompositionID,
			&i.SynapseID,
			&i.TimeWindowWithin,
			&i.TimeWindowUnit,
			&i.DerivedTemplateType,
			&i.DerivedTemplateDomain,
			&i.DerivedTemplateProps,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWatchersByComposition = `-- name: GetWatchersByComposition :many
SELECT pwc.id, pwc.synapse_id, pwc.depth, pwc.min_count, pwc.derived_types, pwc.domains, pwc.created_at
FROM pattern_watcher_configs pwc
JOIN watcher_composition_links wcl ON pwc.id = wcl.pattern_watcher_id
WHERE wcl.composition_id = $1
`

func (q *Queries) GetWatchersByComposition(ctx context.Context, compositionID string) ([]PatternWatcherConfig, error) {
	rows, err := q.db.Query(ctx, getWatchersByComposition, compositionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PatternWatcherConfig{}
	for rows.Next() {
		var i PatternWatcherConfig
		if err := rows.Scan(
			&i.ID,
			&i.SynapseID,
			&i.Depth,
			&i.MinCount,
			&i.DerivedTypes,
			&i.Domains,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWatcherCompositionLinks = `-- name: ListWatcherCompositionLinks :many
SELECT pattern_watcher_id, composition_id FROM watcher_composition_links
WHERE pattern_watcher_id IN (
    SELECT id FROM pattern_watcher_configs WHERE synapse_id = $1
)
`

func (q *Queries) ListWatcherCompositionLinks(ctx context.Context, synapseID string) ([]WatcherCompositionLink, error) {
	rows, err := q.db.Query(ctx, listWatcherCompositionLinks, synapseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WatcherCompositionLink{}
	for rows.Next() {
		var i WatcherCompositionLink
		if err := rows.Scan(&i.PatternWatcherID, &i.CompositionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
